### ISSUE TITLE
Multi filters support

### ISSUE THREAD

**Issue by pascalduez** [pascalduez/SassyFilters#1]
Ongoing work in the `multi-filters` branch.

Provide tools to apply a set of different filters to an element:

E.g:

``` scss
.test--multi .target {
  -webkit-filter: blur(5px) brightness(3) invert(1);
  filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="custom"><feGaussianBlur stdDeviation="5" edgeMode="none"/><feComponentTransfer><feFuncR type="linear" slope="3"/><feFuncG type="linear" slope="3"/><feFuncB type="linear" slope="3"/></feComponentTransfer><feComponentTransfer><feFuncR type="table" tableValues="1 0"/><feFuncG type="table" tableValues="1 0"/><feFuncB type="table" tableValues="1 0"/></feComponentTransfer></filter></svg>#custom');
  -ms-filter: "progid:DXImageTransform.Microsoft.Blur(pixelRadius=5), progid:DXImageTransform.Microsoft.Invert(invert=1)";
  filter: progid:DXImageTransform.Microsoft.Blur(pixelRadius=5) progid:DXImageTransform.Microsoft.Invert(invert=1);
}
```

A space separated list of functions for CSS filters. 
All filters wrapped in a single SVG for SVG filters. 
A space separated list of functions for lt-ie8. 
A comma separated list of functions for gte-ie8.
